# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nod.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'nod.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tnod.proto\x12\x03nod\"4\n\x0b\x46ileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x13\n\x0borigin_node\x18\x02 \x01(\t\"@\n\x0c\x46ileResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\x12\x10\n\x08location\x18\x03 \x01(\t\"\'\n\x10ListFilesRequest\x12\x13\n\x0borigin_node\x18\x01 \x01(\t\"\"\n\x11ListFilesResponse\x12\r\n\x05\x66iles\x18\x01 \x03(\t2}\n\x0bNodeService\x12\x32\n\x0bRequestFile\x12\x10.nod.FileRequest\x1a\x11.nod.FileResponse\x12:\n\tListFiles\x12\x15.nod.ListFilesRequest\x1a\x16.nod.ListFilesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nod_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEREQUEST']._serialized_start=18
  _globals['_FILEREQUEST']._serialized_end=70
  _globals['_FILERESPONSE']._serialized_start=72
  _globals['_FILERESPONSE']._serialized_end=136
  _globals['_LISTFILESREQUEST']._serialized_start=138
  _globals['_LISTFILESREQUEST']._serialized_end=177
  _globals['_LISTFILESRESPONSE']._serialized_start=179
  _globals['_LISTFILESRESPONSE']._serialized_end=213
  _globals['_NODESERVICE']._serialized_start=215
  _globals['_NODESERVICE']._serialized_end=340
# @@protoc_insertion_point(module_scope)
